"""
rootx.webpanel
==============
Localhost web panel for ROOT//X TOOLKIT.
Launched from CLI, accessible at http://127.0.0.1:PORT
Requires a one-time session token generated by CLI.
"""
from .server import WebPanelServer, generate_session_token

__all__ = ["WebPanelServer", "generate_session_token"]
